/* =========================================================
   BIZPILOT AI
   AI ASSISTANT
   js/assistant.js
========================================================= */

document.addEventListener("DOMContentLoaded", () => {

    const chatForm =
        document.getElementById("aiChatForm");

    const chatInput =
        document.getElementById("aiChatInput");

    const chatMessages =
        document.getElementById("aiChatMessages");

    const newChatBtn =
        document.getElementById("newChatBtn");


    /* =====================================================
       SAMPLE AI RESPONSES
    ===================================================== */

    const responses = {

        "How is my business performing this month?":
            "Your business is performing well this month. Revenue is $84,620 with expenses of $18,420, giving you an estimated net profit of $66,200 and a strong 78.2% profit margin.",


        "Show me my biggest expenses.":
            "Your largest recent expenses include Google Ads at $780, Facebook Ads at $620, Business Flight at $1,240, and software subscriptions such as Adobe Creative Cloud and Notion.",


        "Which invoices need my attention?":
            "You currently have several invoices that may need attention. I recommend reviewing overdue invoices first and following up with customers who have outstanding balances.",


        "How can I improve my cash flow?":
            "A few quick improvements could help: follow up on overdue invoices, shorten payment terms for new customers, review recurring subscriptions, and prioritize high-value invoices.",


        "Find expenses that I could reduce.":
            "Your marketing and software expenses are good places to start. Review recurring software subscriptions and compare your advertising spend against the revenue generated by each campaign.",


        "Analyze my unpaid invoices.":
            "I recommend prioritizing overdue invoices by amount and age. Start with your highest-value overdue invoices, then send payment reminders to customers with older balances.",


        "Give me three ways to grow revenue.":
            "Three opportunities: increase repeat purchases from existing customers, improve follow-up on unpaid invoices, and invest more in the marketing channels that generate your highest return.",

    };


    /* =====================================================
       DEFAULT RESPONSE
    ===================================================== */

    function getResponse(message) {

        const cleanMessage =
            message.trim();


        if (responses[cleanMessage]) {

            return responses[cleanMessage];

        }


        const text =
            cleanMessage.toLowerCase();


        if (
            text.includes("revenue") ||
            text.includes("sales")
        ) {

            return "Your current revenue is $84,620. Revenue is trending positively, so I recommend identifying which customers and services are contributing the most to this growth.";

        }


        if (
            text.includes("expense") ||
            text.includes("spending") ||
            text.includes("cost")
        ) {

            return "Your current expenses are $18,420. Marketing, travel, and software are some of the key categories worth reviewing for potential savings.";

        }


        if (
            text.includes("invoice") ||
            text.includes("payment")
        ) {

            return "I can help you review invoices and payment activity. Start by checking overdue invoices and following up with customers who have outstanding balances.";

        }


        if (
            text.includes("customer") ||
            text.includes("client")
        ) {

            return "Your customer data can help identify your highest-value clients and repeat customers. Focus on retention and timely follow-ups to improve revenue.";

        }


        if (
            text.includes("profit") ||
            text.includes("margin")
        ) {

            return "Your estimated net profit is $66,200 with a 78.2% profit margin. That's a strong margin, but reviewing recurring costs could help maintain or improve it.";

        }


        return "I can help you analyze your revenue, expenses, invoices, customers, cash flow, and overall business performance. Try asking me something specific about your business.";

    }


    /* =====================================================
       ADD MESSAGE
    ===================================================== */

    function addMessage(
        message,
        type = "assistant"
    ) {

        const messageWrapper =
            document.createElement("div");


        messageWrapper.className =
            `ai-message ${type}`;


        if (type === "assistant") {

            messageWrapper.innerHTML = `

                <div class="ai-message-avatar">
                    ✦
                </div>

                <div class="ai-message-content">

                    <span class="ai-message-name">
                        BizPilot AI
                    </span>

                    <div class="ai-message-bubble">

                        <p></p>

                    </div>

                </div>

            `;

        } else {

            messageWrapper.innerHTML = `

                <div class="ai-message-content">

                    <div class="ai-message-bubble">

                        <p></p>

                    </div>

                </div>

            `;

        }


        const paragraph =
            messageWrapper.querySelector("p");


        paragraph.textContent =
            message;


        chatMessages.appendChild(
            messageWrapper
        );


        scrollToBottom();

        return messageWrapper;

    }


    /* =====================================================
       TYPING INDICATOR
    ===================================================== */

    function showTyping() {

        const typing =
            document.createElement("div");


        typing.className =
            "ai-message assistant ai-typing-message";


        typing.innerHTML = `

            <div class="ai-message-avatar">
                ✦
            </div>

            <div class="ai-message-content">

                <span class="ai-message-name">
                    BizPilot AI
                </span>

                <div class="ai-message-bubble ai-typing">

                    <span></span>
                    <span></span>
                    <span></span>

                </div>

            </div>

        `;


        chatMessages.appendChild(
            typing
        );


        scrollToBottom();


        return typing;

    }


    /* =====================================================
       SCROLL
    ===================================================== */

    function scrollToBottom() {

        if (!chatMessages) return;


        chatMessages.scrollTo({

            top:
                chatMessages.scrollHeight,

            behavior:
                "smooth"

        });

    }


    /* =====================================================
       SEND MESSAGE
    ===================================================== */

    function sendMessage(message) {

        if (!message) return;


        addMessage(
            message,
            "user"
        );


        chatInput.value = "";


        const typing =
            showTyping();


        const response =
            getResponse(message);


        setTimeout(() => {

            typing.remove();


            addMessage(
                response,
                "assistant"
            );

        }, 900);

    }


    /* =====================================================
       FORM SUBMIT
    ===================================================== */

    if (chatForm) {

        chatForm.addEventListener(
            "submit",
            event => {

                event.preventDefault();


                const message =
                    chatInput.value.trim();


                if (!message) {

                    chatInput.focus();

                    return;

                }


                sendMessage(message);

            }
        );

    }


    /* =====================================================
       ENTER KEY
    ===================================================== */

    if (chatInput) {

        chatInput.addEventListener(
            "keydown",
            event => {

                if (
                    event.key === "Enter" &&
                    !event.shiftKey
                ) {

                    event.preventDefault();

                    chatForm.requestSubmit();

                }

            }
        );

    }


    /* =====================================================
       QUICK PROMPTS
    ===================================================== */

    const promptButtons =
        document.querySelectorAll(
            ".ai-prompt-btn"
        );


    promptButtons.forEach(button => {

        button.addEventListener(
            "click",
            () => {

                const prompt =
                    button.dataset.prompt;


                if (!prompt) return;


                sendMessage(prompt);

            }
        );

    });


    /* =====================================================
       AI SUGGESTIONS
    ===================================================== */

    const suggestionButtons =
        document.querySelectorAll(
            ".ai-suggestion-item"
        );


    suggestionButtons.forEach(button => {

        button.addEventListener(
            "click",
            () => {

                const prompt =
                    button.dataset.prompt;


                if (!prompt) return;


                sendMessage(prompt);

            }
        );

    });


    /* =====================================================
       NEW CHAT
    ===================================================== */

    if (newChatBtn) {

        newChatBtn.addEventListener(
            "click",
            () => {

                const userMessages =
                    chatMessages.querySelectorAll(
                        ".ai-message.user"
                    );


                const generatedMessages =
                    chatMessages.querySelectorAll(
                        ".ai-message.assistant:not(:first-child)"
                    );


                userMessages.forEach(
                    message => message.remove()
                );


                generatedMessages.forEach(
                    message => message.remove()
                );


                const typingMessages =
                    chatMessages.querySelectorAll(
                        ".ai-typing-message"
                    );


                typingMessages.forEach(
                    message => message.remove()
                );


                chatInput.value = "";


                scrollToBottom();


                chatInput.focus();

            }
        );

    }


    /* =====================================================
       SESSION STORAGE PROMPT
    ===================================================== */

    const savedPrompt =
        sessionStorage.getItem(
            "aiPrompt"
        );


    if (savedPrompt) {

        sessionStorage.removeItem(
            "aiPrompt"
        );


        setTimeout(() => {

            if (chatInput) {

                chatInput.value =
                    savedPrompt;

                chatInput.focus();

            }

        }, 300);

    }


    /* =====================================================
       INITIALIZE
    ===================================================== */

    console.log(
        "BizPilot AI Assistant initialized."
    );

});
